# Generated by Django 4.1.3 on 2022-11-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_topartist_fans_topartist_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrelease',
            name='img',
            field=models.ImageField(null=True, upload_to='media/categories/'),
        ),
    ]
