# Generated by Django 4.1.3 on 2022-11-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(null=True, upload_to='media/hindi_songs/'),
        ),
    ]
