# Generated by Django 4.1.3 on 2022-11-26 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0005_alter_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='movie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music_app.newrelease'),
        ),
    ]
